### ISSUE TITLE
Option fields

### ISSUE THREAD

**Issue by ycuk** [Synphonyte/leptos-struct-table#7]
After upgrade leptos to 0.4 and leptos-struct-table to 0.3 I have errors for each Option field:

```
error[E0382]: borrow of partially moved value: `item`
  --> src/profile/list.rs:15:10
   |
15 | #[derive(TableComponent, Serialize, Deserialize, Debug, Clone, PartialEq, Default)]
   |          ^^^^^^^^^^^^^^
   |          |
   |          value partially moved into closure here
   |          variable partially moved due to use in closure
   |          value borrowed here after partial move
   |
   = note: partial move occurs because `item.phone1` has type `std::option::Option<std::string::String>`, which does not implement the `Copy` trait
   = note: this error originates in the derive macro `TableComponent` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0382]: use of moved value: `item.phone1`
  --> src/profile/list.rs:15:10
   |
15 | #[derive(TableComponent, Serialize, Deserialize, Debug, Clone, PartialEq, Default)]
   |          ^^^^^^^^^^^^^^
   |          |
   |          value moved into closure here
   |          variable moved due to use in closure
   |          use occurs due to use in closure
   |          value used here after move
   |
   = note: move occurs because `item.phone1` has type `std::option::Option<std::string::String>`, which does not implement the `Copy` trait
   = note: this error originates in the macro `view` (in Nightly builds, run with -Z macro-backtrace for more info)
```

```rust
#[derive(TableComponent, Serialize, Deserialize, Debug, Clone, PartialEq, Default)]
#[table(sortable, classes_provider = "BootstrapClassesPreset")]
pub struct Profile {
    ...
    #[table(title = "P1", none_value = "-")]
    pub phone1: Option<String>,
    ...
}
```

**Comment by JoelBeicher** [comment]
Ahh yes, I just tried it on the simple example. Turns out we only tested with Copy types. Thanks for reporting.
Should be fixed with v0.3.1.
I'm closing this. If it's still not working for whatever reason, you can just reopen this issue.

**Comment by ycuk** [comment]
Yep, partially fixed

This error still appears:
```
error[E0382]: borrow of partially moved value: `item`
  --> src/profile/list.rs:15:10
   |
15 | #[derive(TableComponent, Serialize, Deserialize, Debug, Clone, PartialEq, Default)]
   |          ^^^^^^^^^^^^^^
   |          |
   |          value partially moved into closure here
   |          variable partially moved due to use in closure
   |          value borrowed here after partial move
   |
   = note: partial move occurs because `item.phone1` has type `std::option::Option<std::string::String>`, which does not implement the `Copy` trait
   = note: this error originates in the derive macro `TableComponent` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This error disappeared:
```
error[E0382]: use of moved value: `item.phone1`
  --> src/profile/list.rs:15:10
   |
15 | #[derive(TableComponent, Serialize, Deserialize, Debug, Clone, PartialEq, Default)]
   |          ^^^^^^^^^^^^^^
   |          |
   |          value moved into closure here
   |          variable moved due to use in closure
   |          use occurs due to use in closure
   |          value used here after move
   |
   = note: move occurs because `item.phone1` has type `std::option::Option<std::string::String>`, which does not implement the `Copy` trait
   = note: this error originates in the macro `view` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by JoelBeicher** [comment]
Hey are you positiv that you're using the updated version? If so and it still doesn't work, could you try running the simple example and see what you get, bc it seems to work for me.

**Comment by ycuk** [comment]
Yes, I see log
```
...
Compiling leptos-struct-table-macro v0.4.1
...
Compiling leptos-struct-table v0.3.1
...
```

Ok, error appears when I add `renderer` and `FieldGetter`

```rust
#[derive(PartialEq, PartialOrd, Clone, Debug, Default)]
pub struct Link {
    text: String,
    href: i64,
}

#[component]
pub fn ObjectLinkTableCellRenderer(
    cx: Scope,
    #[prop(into)]
    class: MaybeSignal<String>,
    #[prop(into)]
    value: MaybeSignal<Link>,
    index: usize,
) -> impl IntoView {
    view! { cx, <td key=index class=class>"-"</td> }
}

#[derive(TableComponent, Serialize, Deserialize, Debug, Clone, Default, PartialEq)]
#[table(sortable)]
pub struct Book {
    #[table(key)]
    pub id: i64,
    pub title: String,
    pub author: String,
    #[table(none_value = "-")]
    pub publish_date: Option<NaiveDate>,
    #[table(title = "D", none_value = "-")]
    pub description: Option<String>,
    #[serde(skip_deserializing)]
    #[table(skip)]
    pub hidden_field: String,
    #[serde(skip_deserializing)]
    #[table(title = "Link", renderer = "ObjectLinkTableCellRenderer")]
    pub link: FieldGetter<Link>,
}

impl Book {
    pub fn link(&self) -> Link {
        Link {
            text: self.title.clone(),
            href: self.id.clone(),
        }
    }
}
```

But the error still points to `Option` field

```
error[E0382]: borrow of partially moved value: `item`
  --> src/main.rs:31:10
   |
31 | #[derive(TableComponent, Serialize, Deserialize, Debug, Clone, Default, PartialEq)]
   |          ^^^^^^^^^^^^^^
   |          |
   |          value partially moved into closure here
   |          variable partially moved due to use in closure
   |          value borrowed here after partial move
   |
   = note: partial move occurs because `item.description` has type `std::option::Option<std::string::String>`, which does not implement the `Copy` trait
   = note: this error originates in the derive macro `TableComponent` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by JoelBeicher** [comment]
Please try now with version 0.3.2. Should be fixed. Hopefully 🙈

**Comment by ycuk** [comment]
Fixed. Thank you!
